export * from './useCreatePage2'
export * from './useDeletePage2'
export * from './useDeletePages2'
export * from './usePage2'
export * from './usePages2'
export * from './usePages2ByParent'
export * from './useUpdatePage2'
export * from './useUpdatePage2Image'