export * from './useCreatePage1'
export * from './useDeletePage1'
export * from './useDeletePages1'
export * from './usePage1'
export * from './usePages1'
export * from './useUpdatePage1'
export * from './useUpdatePage1Image'
export * from './usePages1ByParent'